# Generated by Django 5.1.5 on 2025-05-06 21:07

import authentication.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_id'),
        ('socialaccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deletion_type', models.CharField(choices=[('user', 'User Account'), ('social_auth', 'Social Auth Account')], max_length=20)),
                ('scheduled_time', models.DateTimeField(default=authentication.models.default_scheduled_time)),
                ('cancelled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
