# Generated by Django 5.2 on 2025-05-07 18:32

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_scheduleddeletion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleddeletion',
            name='scheduled_time',
        ),
        migrations.AddField(
            model_name='scheduleddeletion',
            name='scheduled_for',
            field=models.DateTimeField(default=authentication.models.default_scheduled_time),
        ),
    ]
