# Generated by Django 5.2.1 on 2025-05-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_scheduleddeletion_social_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleddeletion',
            name='deletion_type',
            field=models.CharField(choices=[('user', 'User Account'), ('social_account', 'Social Auth Account')], max_length=20),
        ),
    ]
