# Generated by Django 5.2.1 on 2025-05-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_scheduleddeletion_deletion_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='onboarding_step',
            field=models.IntegerField(default=0),
        ),
    ]
