# Generated by Django 5.2 on 2025-05-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_customuser_is_onboarded_customuser_onboarding_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='onboarding_step',
            field=models.IntegerField(default=1),
        ),
    ]
