# Generated by Django 5.2 on 2025-05-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_customuser_onboarding_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('landlord', 'Landlord'), ('tenant', 'Tenant'), ('agent', 'Agent')], default='tenant', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.ManyToManyField(related_name='user_type', to='authentication.usertype'),
        ),
    ]
