# Generated by Django 5.2 on 2025-05-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_usertype_remove_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.ManyToManyField(related_name='users', to='authentication.usertype'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='name',
            field=models.CharField(choices=[('landlord', 'Landlord'), ('tenant', 'Tenant'), ('agent', 'Agent')], db_index=True, default='tenant', max_length=20, unique=True),
        ),
    ]
