# Generated by Django 5.2 on 2025-05-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.CharField(choices=[('nigeria', 'Nigeria')], default='nigeria', max_length=100),
        ),
    ]
