# Generated by Django 5.2 on 2025-05-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_date_added_property_date_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='featured',
            field=models.BooleanField(default=False, help_text='Designates if this property is featured on the site.'),
        ),
    ]
