# Generated by Django 5.2.1 on 2025-05-15 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('condo', 'Condo'), ('townhouse', 'Townhouse'), ('duplex', 'Duplex'), ('studio', 'Studio'), ('villa', 'Villa'), ('self_contained', 'Self Contained'), ('room and parlour', 'Room and Parlour'), ('shared accommodation', 'Shared Accommodation'), ('office space', 'Office Space'), ('commercial property', 'Commercial Property'), ('land', 'Land')], max_length=50)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preferred_location', models.CharField(max_length=255)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('lease_duration', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
