# Generated by Django 5.2 on 2025-05-16 19:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_tenantprofile_delete_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlordprofile',
            name='documents',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='landlord_documents/'),
        ),
    ]
