# Generated by Django 5.2 on 2025-05-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_alter_landlordprofile_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='lease_interval',
            field=models.CharField(blank=True, choices=[('month', 'Month'), ('year', 'Year')], default='year', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='service_states',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='preferred_property_type',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
