# Generated by Django 5.2 on 2025-05-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_tenantprofile_lease_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantprofile',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
