# Generated by Django 5.2 on 2025-05-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0005_alter_tenantprofile_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='agency_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='agency_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
