# Generated by Django 5.2.1 on 2025-05-17 01:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_alter_agentprofile_agency_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlordprofile',
            name='documents',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='documents'),
        ),
    ]
